{
 "title": "ET-7044_Control-Dashboard",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30m",
 "panels": [
  {
   "title": "ET7044_D0 (進風風扇)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.ET7044_D0.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D1 (加濕器)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.ET7044_D1.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D2 (排風風扇)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.ET7044_D2.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D3 (未安裝)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.ET7044_D3.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D0 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "target": "db.ET7044_D0.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D1 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "target": "db.ET7044_D1.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D2 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "target": "db.ET7044_D2.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D3 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "target": "db.ET7044_D3.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D4 (未安裝)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.ET7044_D4.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D5 (未安裝)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.ET7044_D5.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D6 (未安裝)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.ET7044_D6.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D7 (未安裝)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.ET7044_D7.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D5 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "db.ET7044_D5.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D6 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "target": "db.ET7044_D6.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D7 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "db.ET7044_D7.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D7 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "target": "db.ET7044_D7.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}