{
 "title": "UPS_Route_Current-DashBoard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "UPS_A-輸入電流線路_A",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$IN_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸入電流線路_A(備載比例)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$IN_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸入電流線路_A",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$IN_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸入電流線路_A(備載比例)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$IN_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸入電流線路_B",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$IN_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸入電流線路_B(備載比例)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$IN_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸入電流線路_B",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$IN_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸入電流線路_B(備載比例)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$IN_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_A",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_A(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-歷史電流_A",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_A",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_A(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-歷史電流_A",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_B",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_B(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-歷史電流_B",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_B",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_B(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-歷史電流_B",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_C",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_C\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_C(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_C\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-歷史電流_C",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 24 },
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_C\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_C",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_C\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_C(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_C\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-歷史電流_C",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_C\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_D",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_D\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_D(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_D\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-歷史電流_D",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 29 },
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_D\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_D",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_D\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_D(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_D\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-歷史電流_D",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 29 },
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_D\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_E",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_E\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_E(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_E\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-歷史電流_E",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 34 },
   "targets": [
    {
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_E\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_E",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 500},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_E\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_E(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_E\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-歷史電流_E",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 34 },
   "targets": [
    {
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_E\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}