import os, sys

os.system("apt-get update -y")
os.system('echo "deb https://packages.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list')
os.system("apt-get install -y apt-transport-https curl")
os.system("curl https://packages.grafana.com/gpg.key | apt-key add -")
os.system("apt-get update -y")
os.system("apt-get install -y grafana")
os.system("service grafana-server start")
os.system("update-rc.d grafana-server defaults")
os.system("apt-get install -y mysql-server mysql-client")
os.system("apt-get install -y python3-dev python3-pip libmysqlclient-dev")
os.system("apt-get install -y build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev")
os.system("pip3 install mysqlclient")
os.system("apt-get install supervisor")
os.system("cp ./dataTransport.conf /etc/supervisor/")
os.system("service supervisor restart")