{
 "title": "Air_Condiction-DashBoard",
 "time": { "from": "2018-10-23T10:33:22.059Z", "to": "2018-10-23T10:34:28.773Z" },
 "panels": [
  {
   "title": "air_condiction-Temperature",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.air_conditioner_vent.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Temperature\", \"value\" : \"$Temperature\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "air_condiction-Humidity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.air_conditioner_vent.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Humidity\", \"value\" : \"$Humidity\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Ait_condition-Currents",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "target": "db.current.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"currents\", \"value\" : \"$currents\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "偵測節點溫度",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "target": "db.current.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Temperature\", \"value\" : \"$Temperature\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "偵測節點濕度",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.current.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Humi\", \"value\" : \"$Humidity\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Air-condiction_Current(歷史電流表單)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "target": "db.current.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :500},\n{\"$project\" : {\"name\" : \"currents\", \"value\" : \"$currents\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "最新10筆電流資料",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "target": "db.current.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :15},\n{\"$project\" : {\"name\" : \"currents\", \"value\" : \"$currents\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Air-condiction_Temperature(歷史溫度表單)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "target": "db.current.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :500},\n{\"$project\" : {\"name\" : \"Temperature\", \"value\" : \"$Temperature\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "最新15筆溫度資料",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 23 },
   "targets": [
    {
     "target": "db.air_conditioner_vent.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :15},\n{\"$project\" : {\"name\" : \"Temperature\", \"value\" : \"$Temperature\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Air-condiction_Current(歷史濕度表單)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "target": "db.current.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :500},\n{\"$project\" : {\"name\" : \"Humidity\", \"value\" : \"$Humidity\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "最新15筆濕度資料",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 36 },
   "targets": [
    {
     "target": "db.air_conditioner_vent.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :15},\n{\"$project\" : {\"name\" : \"Humidity\", \"value\" : \"$Humidity\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}