{
 "title": "DL303-DashBoard",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DL-303_Temperature(即時環境溫度)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.DL303_TC.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Temp\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL303_Humidity(即時環境濕度)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.DL303_RH.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Humi\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL303-CO2(即時二氧化碳濃度)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.DL303_CO2.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"CO2\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL303-CO2(即時露點溫度)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.DL303_DC.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"DC\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL-303_Temperature(溫度歷史圖表)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "db.DL303_TC.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 360},\n{\"$project\" : {\"name\" : \"Temp\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL-303_Temperature(最新15筆溫度資料)",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "target": "db.DL303_TC.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Temp\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL303_Humidity(濕度歷史列表)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "target": "db.DL303_RH.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 350},\n{\"$project\" : {\"name\" : \"Humi\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL-303_Humidity(最新15筆濕度資料)",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 18 },
   "targets": [
    {
     "target": "db.DL303_RH.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Humi\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL303-CO2(二氧化碳濃度歷史列表)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "target": "db.DL303_CO2.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 360},\n{\"$project\" : {\"name\" : \"CO2\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL-303_CO2(最新15筆二氧化碳濃度資料)",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 31 },
   "targets": [
    {
     "target": "db.DL303_CO2.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"CO2\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL303_DC(即時露點溫度)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "db.DL303_DC.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 360},\n{\"$project\" : {\"name\" : \"DC\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL-303_DC(最新15筆露點溫度資料)",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 44 },
   "targets": [
    {
     "target": "db.DL303_DC.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"DC\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}