{
 "title": "UPS_B-DashBoard",
 "time": { "from": "2018-10-23T11:25:57.228Z", "to": "2018-10-23T11:34:19.767Z" },
 "panels": [
  {
   "title": "UPS_B - Connect_locate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"connect\", \"value\" : \"$connect_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - Life",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"input_Line\", \"value\" : \"$ups_Life_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"input_Line\", \"value\" : \"$battery_B.status.batteryTemp_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B -Batter_Charge_Mode",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$battery_B.status.batteryCharge_Mode_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B -Battery_Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 4 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$battery_B.status.batteryStatus_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B -Battery_Health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$battery_B.status.batteryHealth_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - Input_Line",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"input_Line\", \"value\" : \"$input_B.inputLine_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - output_status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$output_B.systemMode_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - Input_Voltage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$input_B.inputVolt_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - Input_Frequency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$input_B.inputFreq_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - output_Line",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$output_B.outputLine_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - output_Bmp",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$output_B.outputAmp_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - output_Voltage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$output_B.outputVolt_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - output_Frequency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$output_B.outputFreq_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B -Load_Percent",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$output_B.outputWatt_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B -Load_Percent",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 16 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$output_B.outputPercent_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B -Battery_Volt",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 16 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$battery_B.status.batteryVolt_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B -Battery_Remain",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 16 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$battery_B.status.batteryRemain_Percent_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-Battery-LastChange_Date",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
   "content": "<font color=gray size=7> 上次更換電池日期 : </font>"
  },
  {
   "title": "Last_battery_Year",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_B.lastChange.lastBattery_Year_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Last_battery_Month",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_B.lastChange.lastBattery_Mon_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Last_battery_day",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_B.lastChange.lastBattery_Day_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-Battery-NextChange_Date",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
   "content": "<font color=gray size=7> 下次更換電池日期 : </font>"
  },
  {
   "title": "Next_battery_Year",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_B.nextChange.nextBattery_Year_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Next_battery_Month",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_B.nextChange.nextBattery_Mon_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Next_battery_Day",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_B.nextChange.nextBattery_Day_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-input / output Voltage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :864},\n{\"$project\" : {\"name\" : \"inputVolt_B\", \"value\" : \"$input_B.inputVolt_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :864},\n{\"$project\" : {\"name\" : \"outputVolt_B\", \"value\" : \"$output_B.outputVolt_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-tempurate / output Current",
   "type": "graph",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :864},\n{\"$project\" : {\"name\" : \"outputAmp_B\", \"value\" : \"$output_B.outputAmp_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :864},\n{\"$project\" : {\"name\" : \"Temperature\", \"value\" : \"$battery_B.status.batteryTemp_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-OutWatt / OutPercent",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :300},\n{\"$project\" : {\"name\" : \"inputWatt_B\", \"value\" : \"$output_B.outputWatt_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :300},\n{\"$project\" : {\"name\" : \"inputPercent_B\", \"value\" : \"$output_B.outputPercent_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}