{
 "title": "UPS_A-DashBoard",
 "time": { "from": "2018-10-23T11:25:57.214Z", "to": "2018-10-23T11:31:39.749Z" },
 "panels": [
  {
   "title": "UPS_A - Connect_locate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"connect\", \"value\" : \"$connect_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A - Life",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"input_Line\", \"value\" : \"$ups_Life_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A - Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"input_Line\", \"value\" : \"$battery_A.status.batteryTemp_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A -Batter_Charge_Mode",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$battery_A.status.batteryCharge_Mode_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A -Battery_Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 4 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$battery_A.status.batteryStatus_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A -Battery_Health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$battery_A.status.batteryHealth_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A - Input_Line",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"input_Line\", \"value\" : \"$input_A.inputLine_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A - output_status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$output_A.systemMode_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A - Input_Voltage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$input_A.inputVolt_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A - Input_Frequency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$input_A.inputFreq_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A - output_Line",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$output_A.outputLine_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A - output_Amp",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$output_A.outputAmp_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A - output_Voltage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$output_A.outputVolt_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A - output_Frequency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$output_A.outputFreq_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A -Load_Percent",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$output_A.outputWatt_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A -Load_Percent",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 16 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$output_A.outputPercent_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A -Battery_Volt",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 16 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$battery_A.status.batteryVolt_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A -Battery_Remain",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 16 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$battery_A.status.batteryRemain_Percent_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-Battery-LastChange_Date",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
   "content": "<font color=gray size=7> 上次更換電池日期 : </font>"
  },
  {
   "title": "Last_Aattery_Year",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_A.lastChange.lastBattery_Year_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Last_Aattery_Month",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_A.lastChange.lastBattery_Mon_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Last_Aattery_day",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_A.lastChange.lastBattery_Day_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-Battery-NextChange_Date",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
   "content": "<font color=gray size=7> 下次更換電池日期 : </font>"
  },
  {
   "title": "Next_Aattery_Year",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_A.nextChange.nextBattery_Year_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Next_Aattery_Month",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_A.nextChange.nextBattery_Mon_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Next_Aattery_Day",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"Year\", \"value\" : \"$battery_A.nextChange.nextBattery_Day_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-input / output Voltage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :864},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$input_A.inputVolt_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :864},\n{\"$project\" : {\"name\" : \"outputVolt_A\", \"value\" : \"$output_A.outputVolt_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-tempurate / output Current",
   "type": "graph",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :864},\n{\"$project\" : {\"name\" : \"outputAmp_A\", \"value\" : \"$output_A.outputAmp_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :864},\n{\"$project\" : {\"name\" : \"Temperature\", \"value\" : \"$battery_A.status.batteryTemp_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-OutWatt / OutPercent",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :300},\n{\"$project\" : {\"name\" : \"inputWatt_A\", \"value\" : \"$output_A.outputWatt_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    },
    {
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :300},\n{\"$project\" : {\"name\" : \"inputPercent_A\", \"value\" : \"$output_A.outputPercent_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}