{
 "title": "冷氣出風口",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "air_condiction-Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Temp\nFROM Air_Condiction\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "air_condiction-Humidity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Humi\nFROM Air_Condiction\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "Ait_condition-Currents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Current\nFROM Power_Meter\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "偵測節點溫度",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Temp\nFROM Power_Meter\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "偵測節點濕度",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Humi\nFROM Power_Meter\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "Air-condiction_Current(歷史電流表單)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Current\nFROM Power_Meter\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "最新10筆電流資料",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT Current AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Meter\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.current.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :15},\n{\"$project\" : {\"name\" : \"currents\", \"value\" : \"$currents\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Air-condiction_Temperature(歷史溫度表單)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Temp\nFROM Power_Meter\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "最新15筆溫度資料",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT Temp AS 溫度, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Meter\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.current.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :15},\n{\"$project\" : {\"name\" : \"Temperature\", \"value\" : \"$Temperature\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Air-condiction_Current(歷史濕度表單)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Humi\nFROM Power_Meter\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "最新15筆濕度資料",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT Humi AS 濕度, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Meter\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.current.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :15},\n{\"$project\" : {\"name\" : \"Humidity\", \"value\" : \"$Humidity\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}