{
 "title": "DL303-DashBoard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DL-303_Temperature(即時環境溫度)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Temp AS \"Count_Log\"\nFROM DL303_TC\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp",
     "target": "db.DL303_TC.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 1},\n{\"$project\" : {\"name\" : \"Temp\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL303_Humidity(即時環境濕度)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Humi\nFROM DL303_RH\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "DL303-CO2(即時二氧化碳濃度)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Co2\nFROM DL303_CO2\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "DL303-Dew_Point(即時露點溫度)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Dew_Point\nFROM DL303_DC\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "DL-303_Temperature(溫度歷史圖表)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Temp\nFROM DL303_TC\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "DL-303_Temperature(最新15筆溫度資料)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT Temp AS 溫度, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM DL303_TC \nORDER BY Time_Stamp DESC\nLIMIT 15;"
    }
   ]
  },
  {
   "title": "DL303_Humidity(濕度歷史列表)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Humi\nFROM DL303_RH\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "DL-303_Humidity(最新15筆濕度資料)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT Humi AS 濕度, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM DL303_RH\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.DL303_RH.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Humi\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL303-CO2(二氧化碳濃度歷史列表)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Co2\nFROM DL303_CO2\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "DL-303_CO2(最新15筆二氧化碳濃度資料)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT Co2 AS 二氧化碳濃度, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM DL303_CO2\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.DL303_CO2.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"CO2\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DL303_DC(即時露點溫度)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Dew_Point\nFROM DL303_DC\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "DL-303_DC(最新15筆露點溫度資料)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT Dew_Point AS 結露溫度, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM DL303_DC\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.DL303_DC.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"DC\", \"value\" : \"$data\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}