{
 "title": "ET-7044_Control-Dashboard",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ET7044_D0 (進風風扇)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  SW1\nFROM ET7044\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "ET7044_D1 (加濕器)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  SW2\nFROM ET7044\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "ET7044_D2 (排風風扇)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  SW2\nFROM ET7044\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "ET7044_D3 (未安裝)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  SW4\nFROM ET7044\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "ET7044_D0 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT SW1 AS 狀態, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM ET7044\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.ET7044_D0.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D1 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT SW2 AS 狀態, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM ET7044\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.ET7044_D1.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D2 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT SW3 AS 狀態, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM ET7044\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.ET7044_D2.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D3 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT SW4 AS 狀態, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM ET7044\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.ET7044_D3.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D4 (未安裝)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  SW5\nFROM ET7044\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "ET7044_D5 (未安裝)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  SW6\nFROM ET7044\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "ET7044_D6 (未安裝)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  SW7\nFROM ET7044\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "ET7044_D7 (未安裝)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  SW8\nFROM ET7044\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "ET7044_D4 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT SW6 AS 狀態, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM ET7044\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.ET7044_D5.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D5 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT SW6 AS 狀態, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM ET7044\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.ET7044_D6.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D6 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT SW7 AS 狀態, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM ET7044\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.ET7044_D7.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ET7044_D7 (開關設備歷史)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT SW8 AS 狀態, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM ET7044\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.ET7044_D7.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 5},\n{\"$project\" : {\"name\" : \"Status\", \"value\" : \"$status\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}