{
 "title": "UPS_B-DashBoard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "UPS_B - Connect_locate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT Device_Locate FROM UPS_B ORDER BY Time_Stamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "UPS_B - Life",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT Device_Life FROM UPS_B ORDER BY Time_Stamp DESC LIMIT 1;",
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"input_Line\", \"value\" : \"$ups_Life_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Battery_Temp\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B -Batter_Charge_Mode",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT Battery_Charge_Mode FROM UPS_B ORDER BY Time_Stamp DESC LIMIT 1;",
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$battery_A.status.batteryCharge_Mode_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B -Battery_Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 4 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT Battery_Status FROM UPS_B ORDER BY Time_Stamp DESC LIMIT 1;",
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :1},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$battery_A.status.batteryStatus_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B -Battery_Health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT Battery_Health FROM UPS_B ORDER BY Time_Stamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "UPS_B - Input_Line",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Input_Line\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B - output_status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT System_Mode FROM UPS_B ORDER BY Time_Stamp DESC LIMIT 1;\n",
     "target": "db.UPS_Monitor.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" :100},\n{\"$project\" : {\"name\" : \"inputVolt_A\", \"value\" : \"$output_A.systemMode_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B - Input_Voltage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Input_Volt\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B - Input_Frequency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Input_Freq\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B - output_Line",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Output_Line\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B - output_Amp",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Output_Amp\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B - output_Voltage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Output_Volt\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B - output_Frequency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Output_Freq\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B -Load_Percent",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Output_Watt\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B -Load_Percent",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Output_Percent\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B -Battery_Volt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Battery_Volt\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B -Battery_Remain",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Battery_Remain_Percent\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-Battery-LastChange_Date",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "content": "<font color=gray size=7> 上次更換電池日期 : </font>"
  },
  {
   "title": "Last_Aattery_Year",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Battery_Last_Change_Year\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "Last_Aattery_Month",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Battery_Last_Change_Mon\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "Last_Aattery_day",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Battery_Last_Change_Day\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-Battery-NextChange_Date",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 21 },
   "content": "<font color=gray size=7> 下次更換電池日期 : </font>"
  },
  {
   "title": "Next_Aattery_Year",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Battery_Next_Change_Year\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "Next_Aattery_Month",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Battery_Next_Change_Mon\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "Next_Aattery_Day",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Battery_Next_Change_Day\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-input / output Voltage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Input_Volt\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    },
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Output_Volt\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-tempurate / output Current",
   "type": "graph",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Battery_Temp\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    },
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Output_Amp\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-OutWatt / OutPercent",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Output_Watt\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    },
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Output_Percent\nFROM UPS_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  }
 ]
}