{
 "title": "UPS_Route_Current-DashBoard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "UPS_A-輸入電流線路_A",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  In_A\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-輸入電流線路_A(備載比例)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  In_A\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-輸入電流線路_A",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  In_A\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-輸入電流線路_A(備載比例)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  In_A\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-輸入電流線路_B",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  In_B\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-輸入電流線路_B(備載比例)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  In_B\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-輸入電流線路_B",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  In_B\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-輸入電流線路_B(備載比例)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  In_B\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_A",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_A\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_A(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_A\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-歷史電流_A",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT OUT_A AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Box_A\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_A",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_A\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_A(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_A\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-歷史電流_A",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT OUT_A AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Box_B\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_A\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_B",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_B\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_B(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_B\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-歷史電流_B",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT OUT_B AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Box_A\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_B",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_B\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_B(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_B\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-歷史電流_B",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT OUT_B AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Box_B\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_B\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_C",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_C\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_C(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_C\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-歷史電流_C",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT OUT_C AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Box_A\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_C\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_C",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_C\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_C(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_C\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-歷史電流_C",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT OUT_C AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Box_B\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_C\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_D",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_D\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_D(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_D\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-歷史電流_D",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT OUT_D AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Box_A\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_D\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_D",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_D\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_D(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_D\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-歷史電流_D",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT OUT_D AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Box_B\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_D\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_E",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_E\nFROM Power_Box_A\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-輸出電流線路_E(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_E\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_A-歷史電流_E",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT OUT_E AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Box_A\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.cabinet_A.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_E\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_E",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_E\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-輸出電流線路_E(線路附載比)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  Time_Stamp AS \"time\",\n  Out_E\nFROM Power_Box_B\nWHERE\n  $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "UPS_B-歷史電流_E",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT OUT_E AS 電流, DATE_ADD(Time_Stamp, INTERVAL 8 HOUR) AS 更新時間 FROM Power_Box_B\nORDER BY Time_Stamp DESC\nLIMIT 15;",
     "target": "db.cabinet_B.aggregate([\n{\"$sort\": {\"date\" : -1}},\n{\"$limit\" : 15},\n{\"$project\" : {\"name\" : \"Current\", \"value\" : \"$OUT_V110_E\",  \"ts\" : \"$date\",  \"_id\" : 0 }}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}